name: "CI"

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup Biome"
        uses: biomejs/setup-biome@v2
        with:
          version: "2.0.5"
      - name: "Run Biome"
        run: "biome ci ."
  test:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: "Install deps"
        run: "bun install --frozen-lockfile"
      - name: Vérifier si le dossier modules existe
        run: |
          if test -d modules; then
            echo "Le dossier modules existe."
          else
            echo "Le dossier modules est manquant."
            exit 1
          fi
      - name: "Run test"
        run: "bun test"
