on:
  workflow_dispatch: 
  #push:
    #branches:
      #- master
  #pull_request:
    #types: [opened, synchronize, reopened]

name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      # Optionnel si tu veux compiler avant analyse
      - name: Build project
        run: npm run build || echo "No build step"

      - name: Run SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: "."
          projectKey: "my-typescript-project"
          projectName: "My TypeScript Project"

